# Generated by Django 4.2.18 on 2025-03-01 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0001_initial'),
        ('instrutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='codigo_titulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='titulo.titulo'),
        ),
    ]
