# Generated by Django 4.2.18 on 2025-02-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipodeatividade', '0002_alter_tipodeatividade_codigo'),
        ('tipodeatividade', '0003_alter_tipodeatividade_codigo'),
    ]

    operations = [
    ]
