# Generated by Django 4.2.18 on 2025-02-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('codigo', models.AutoField(help_text='Código do Aluno', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição do Aluno', max_length=70)),
            ],
        ),
    ]
