# Generated by Django 4.2.18 on 2025-02-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='codigo',
            new_name='matricula',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='aluno',
            name='datafinal',
            field=models.DateField(blank=True, help_text='Informe a data final do Aluno', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='datainicial',
            field=models.DateField(blank=True, help_text='Informe a data inicial do Aluno', max_length=70, null=True),
        ),
    ]
