# Generated by Django 4.2.18 on 2025-02-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_rename_codigo_aluno_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.AutoField(help_text='Matricula do Aluno', primary_key=True, serialize=False),
        ),
    ]
