# Generated by Django 4.2.18 on 2025-02-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_aluno_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='matricula',
            new_name='codigo',
        ),
    ]
