# Generated by Django 4.2.18 on 2025-02-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_rename_matricula_aluno_codigo'),
        ('aluno', '0014_alter_aluno_data_inicial'),
    ]

    operations = [
    ]
