# Generated by Django 4.2.18 on 2025-02-19 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0001_initial'),
        ('instrutores', '0002_rename_id_instrutores_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrutores',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='instrutores',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='instrutores',
            name='dataNascimento',
            field=models.DateField(blank=True, help_text='Informe a data de nascimento do Instrutor', null=True),
        ),
        migrations.AddField(
            model_name='instrutores',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrutores',
            name='codigo_titulo',
            field=models.ForeignKey(blank=True, db_column='titulo_codigo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='titulo.titulo'),
        ),
        migrations.AlterField(
            model_name='instrutores',
            name='ddd',
            field=models.CharField(help_text='Informe o DDD do telefone do Instrutor', max_length=3),
        ),
        migrations.AlterField(
            model_name='instrutores',
            name='nome',
            field=models.CharField(help_text='Informe o nome do Instrutor', max_length=70),
        ),
        migrations.AlterField(
            model_name='instrutores',
            name='rg',
            field=models.CharField(help_text='Informe o RG do Instrutor', max_length=15),
        ),
        migrations.AlterField(
            model_name='instrutores',
            name='telefone',
            field=models.CharField(help_text='Informe o telefone do Instrutor', max_length=9),
        ),
    ]
