# Generated by Django 4.2.18 on 2025-02-12 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrutores', '0001_initial'),
        ('aluno', '0002_rename_codigo_aluno_matricula_and_more'),
        ('tipodeatividade', '0002_alter_tipodeatividade_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('codigo', models.AutoField(help_text='Código do Titulo', primary_key=True, serialize=False)),
                ('horarioaula', models.TimeField(help_text='Informe o horário da Aula:', max_length=70)),
                ('duracaoaluna', models.DurationField(help_text='Informe a duração da Aula:', max_length=70)),
                ('datainicial', models.DateField(help_text='Informe a data de Inicio:', max_length=70)),
                ('datafinal', models.DateField(blank=True, help_text='Informe a data de Término:', max_length=70, null=True)),
                ('codigo_aluno', models.ForeignKey(blank=True, db_column='codigo_aluno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluno.aluno')),
                ('codigo_intrutores', models.ForeignKey(blank=True, db_column='codigo_intrutores', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instrutores.instrutores')),
                ('codigo_tipoatividade', models.ForeignKey(blank=True, db_column='codigo_tipodeatividade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipodeatividade.tipodeatividade')),
            ],
        ),
    ]
