# Generated by Django 4.2.18 on 2025-02-12 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrutores', '0002_rename_id_instrutores_codigo'),
        ('aluno', '0004_rename_matricula_aluno_codigo'),
        ('turmas', '0003_alter_turmas_id_alter_turmas_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='turmas',
            name='matricula',
        ),
        migrations.AddField(
            model_name='turmas',
            name='codigo_aluno',
            field=models.ForeignKey(blank=True, db_column='codigo_aluno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluno.aluno'),
        ),
        migrations.AddField(
            model_name='turmas',
            name='codigo_instrutor',
            field=models.ForeignKey(blank=True, db_column='codigo_instrutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instrutores.instrutores'),
        ),
    ]
