# Generated by Django 4.2.18 on 2025-02-13 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrutores', '0002_rename_id_instrutores_codigo'),
        ('aluno', '0004_rename_matricula_aluno_codigo'),
        ('tipodeatividade', '0002_alter_tipodeatividade_codigo'),
        ('turmas', '0004_remove_turmas_id_remove_turmas_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmas',
            name='codigo_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='codigo_instrutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrutores.instrutores'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='codigo_tipoatividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipodeatividade.tipodeatividade'),
        ),
    ]
