# Generated by Django 4.2.18 on 2025-02-19 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_rename_matricula_aluno_codigo'),
        ('turmas', '0005_alter_turmas_codigo_aluno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_maricula', models.DateField(default=datetime.datetime(2025, 2, 19, 22, 54, 30, 755968, tzinfo=datetime.timezone.utc), help_text='Informe a data de Inicio da Matrícula:')),
                ('data_fim_matricula', models.DateField(blank=True, help_text='Informe a data de Término da Matrícula:', null=True)),
                ('id_aluno', models.ForeignKey(help_text='Número da matrícula do Aluno.', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('id_turma', models.ForeignKey(help_text='Número da Turma do Aluno.', on_delete=django.db.models.deletion.CASCADE, to='turmas.turmas')),
            ],
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ausencia', models.DateField(default=datetime.datetime(2025, 2, 19, 22, 54, 30, 755968, tzinfo=datetime.timezone.utc), help_text='Informe a data da Ausência:')),
                ('justificativa', models.CharField(help_text='Informe a Justificativa da Ausência:', max_length=200)),
                ('id_aluno', models.ForeignKey(help_text='Número da matrícula do Aluno.', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('id_turma', models.ForeignKey(help_text='Número da Turma do Aluno.', on_delete=django.db.models.deletion.CASCADE, to='turmas.turmas')),
            ],
        ),
    ]
