# Generated by Django 4.2.18 on 2025-02-19 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0006_turmaaluno_ausencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='data_ausencia',
            field=models.DateField(default=datetime.datetime(2025, 2, 19, 22, 58, 11, 108184, tzinfo=datetime.timezone.utc), help_text='Informe a data da Ausência:'),
        ),
        migrations.AlterField(
            model_name='turmaaluno',
            name='data_inicio_maricula',
            field=models.DateField(default=datetime.datetime(2025, 2, 19, 22, 58, 11, 108184, tzinfo=datetime.timezone.utc), help_text='Informe a data de Inicio da Matrícula:'),
        ),
    ]
